# Generated by Django 4.1.3 on 2022-11-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Product',
        ),
    ]
